#!/usr/bin/env bash

set -euo pipefail
shopt -s globstar nullglob

output_file="src/generated/wikilink-index.ts"
mkdir -p "$(dirname "$output_file")"

declare -A wikilink_index

for file in src/site/notes/**/*.{md,mdx}; do
	wikilink_target="${file#src/site/notes/}"
	wikilink_target="${wikilink_target%.*}"

	permalink=$(grep -oP '"permalink"\s*:\s*"\K[^"]+' "$file")
	if grep -qP '"tags"\s*:\s*\[[^]]*"gardenEntry"' "$file"; then
		permalink="/"
	fi
	wikilink_index["$wikilink_target"]="$permalink"
done

function output_wikilink_index() {
	while IFS= read -r wikilink_target; do
		permalink="${wikilink_index[$wikilink_target]}"
		printf '  "%s": "%s",\n' "$wikilink_target" "$permalink"
	done < <(printf '%s\n' "${!wikilink_index[@]}" | LC_ALL=C sort)
}

# This is called a heredoc
cat <<EOF >"$output_file"
// This file is generated by scripts/generate-wikilink-index.sh
// Do not edit this file by hand

export interface WikilinkIndex {
  [wikilinkTarget: string]: string | undefined;
}

export const wikilinkIndex: WikilinkIndex = {
$(output_wikilink_index)
};
EOF

npx prettier --write "$output_file" >/dev/null
