// Maps each Obsidian callout `data-callout` type to the Lucide icon name its
// `--callout-icon` CSS custom property declares, with any "lucide-" prefix
// already stripped. The live site resolves `--callout-icon` with
// `getComputedStyle` in the browser and swaps in the icon client-side;
// Astro instead resolves it here, once, at build time.
//
// Sources, in cascade order (the Eleventy styles, kept until cutover):
//   1. src/site/styles/obsidian-base.scss -- Obsidian's built-in callout
//      types, including alias selectors such as `[data-callout="summary"]`.
//   2. src/site/styles/user/callouts.scss -- custom types generated by the
//      `/sync-callouts` skill from the Obsidian vault.
//
// `test/callout-icons.test.ts` parses those same sources with a real CSS
// parser and fails if this map drifts from them, so re-running
// `/sync-callouts` (which regenerates callouts.scss) can't silently desync
// icons from what actually renders.
//
// Why a literal map instead of reading those sources at build time:
//   - The Markdown pipeline stays independent of stylesheets. Parsing SCSS
//     with a CSS parser is fragile, so that belongs in the test, not the build.
//   - Cutover deletes the Eleventy sources; this map outlives them and
//     becomes the source of truth for callout icons.
//   - The drift test catches a mismatch; it can't prevent one. Having
//     `/sync-callouts` write this map directly would remove the duplication
//     (tracked in REWRITE.md). The skill also writes each type's
//     `--callout-color`; src/styles/content/callouts.css now holds a copy,
//     which the skill must write once the Eleventy Sass goes.
//
// One deliberate departure from those sources: Obsidian's `quote`/`cite`
// callouts declare `quote-glyph`, an Obsidian-only icon that Lucide does not
// ship, so live rendered no icon for them. They use Lucide's `quote` icon
// instead (ADR 0003 phase 2). The drift test lists this override.
//
// `getCalloutIconName` returns the name as-is; resolving it to an actual
// icon (or the empty-`<i>` fallback for a name Lucide doesn't have, such as
// one a future `/sync-callouts` copies from Obsidian) is `lucide-icon.ts`'s
// job.

// The bare `.callout` rule's icon: used by any type with no more specific
// `[data-callout="..."]` rule (for example "note", which has no rule of its
// own in obsidian-base.scss).
export const DEFAULT_CALLOUT_ICON_NAME = "pencil";

export const CALLOUT_ICON_NAMES: Readonly<Record<string, string>> = {
  // From src/site/styles/obsidian-base.scss.
  abstract: "clipboard-list",
  summary: "clipboard-list",
  tldr: "clipboard-list",
  info: "info",
  todo: "check-circle-2",
  important: "flame",
  tip: "flame",
  hint: "flame",
  success: "check",
  check: "check",
  done: "check",
  question: "help-circle",
  help: "help-circle",
  faq: "help-circle",
  warning: "alert-triangle",
  caution: "alert-triangle",
  attention: "alert-triangle",
  failure: "x",
  fail: "x",
  missing: "x",
  danger: "zap",
  error: "zap",
  bug: "bug",
  example: "list",
  // Deliberate override: the source declares `quote-glyph` (see above).
  quote: "quote",
  cite: "quote",

  // From src/site/styles/user/callouts.scss (regenerated by /sync-callouts).
  "ai-text": "bot",
  wikipedia: "book-open",
  highlight: "highlighter",
  remember: "lightbulb",
  aside: "message-square",
  exercise: "pencil-line",
};

/** Resolve a `data-callout` type (already lowercased upstream) to the icon
 * name its `--callout-icon` declares, falling back to the default icon for
 * a type with no specific rule. */
export function getCalloutIconName(calloutType: string): string {
  const type = calloutType.toLowerCase();
  // A callout type such as "constructor" is an *inherited* property of any
  // plain object (Object.prototype.constructor), not a missing one, so a
  // bare CALLOUT_ICON_NAMES[type] lookup would silently return that
  // built-in instead of falling through to the default. Object.hasOwn
  // checks the map's own keys only, the same guard `toTitleCase` in
  // callout.ts uses for its title-case override lookup.
  return Object.hasOwn(CALLOUT_ICON_NAMES, type)
    ? CALLOUT_ICON_NAMES[type]!
    : DEFAULT_CALLOUT_ICON_NAME;
}
