import { glob } from "astro/loaders";
import { defineCollection } from "astro:content";
import { z } from "astro/zod";
import { noteDateSchema } from "./content/note-dates.ts";
import { permalinkSchema } from "./content/permalinks.ts";

const posts = defineCollection({
  loader: glob({
    pattern: "**/*.{md,mdx}",
    base: "./src/site/notes", // This is where our posts live
  }),
  /*
    NOTE: Right now the schema for our post frontmatter is a bit wonky. As much as I'd like to have 100% control over post frontmatter, doing so would require effort I'm unwilling to expend at the moment, so here's how it's gonna be.

    The important top-level frontmatter will be maintained, but everything else will be read from "dg-note-properties" which is our raw obsidian note properties pass on as is, no processing by the digitalgarden plugin.

    Though I'd prefer if properties under "dg-note-properties", and in fact, we can do this by setting `dg-pass-frontmatter` to true, however, doing so risks collisions with plugin computer frontmatter properties. Moreover, in the case of a collision the plugin's computed properties would win, which kinda defeats the point

    For now, we'll keep things like this until the astro rewrite is done and perhaps for some time beyond that, until I decide to move away from the digitalgarden plugin entirely.

    For now though, regarding property access, we can always use zod's transform method to make it more "ergonomic"
  */
  schema: () =>
    z
      .object({
        "dg-publish": z.boolean(), // Most important
        tags: z.array(z.string()), // Solely for checking for "gardenEntry" to determine the home/index page
        "dg-path": z.string(), // The path to our post, auto-generated by the digitalgarden plugin per our plugin settings and path rewrite rules. We do not manually set this
        permalink: permalinkSchema, // The actual URL for a post
        "dg-permalink": z.string(), // Setting this is what allows us full control over the URLs for our posts. Otherwise, the digitalgarden plugin will auto gen the "permalink" property from the "dg-path" property. This property exists solely as a means for user override. The actual URL is set using the "permalink" prop. Must always be manually set to enforce that we determine the URLs, not the plugin.
        hide: z.boolean().optional(), // The publisher writes a note's `dg-hide: true` as `hide: true` (and omits it otherwise). A hidden post is still published; it is only left out of the file tree, as on the Eleventy site.
        "dg-note-properties": z.object({
          title: z.string(),
          description: z.string(),
          tags: z.array(z.string()),
          published: noteDateSchema,
          last_updated: noteDateSchema,
        }),
      })
      .transform(({ "dg-note-properties": rawNoteProps, ...pluginProps }) => ({
        rawNoteProps,
        pluginProps,
      })),
});

export const collections = {
  posts,
};
