import { glob } from "astro/loaders";
import { defineCollection } from "astro:content";
import { z } from "astro/zod";

const posts = defineCollection({
  loader: glob({
    pattern: "**/*.{md,mdx}",
    base: "./src/site/notes", // This is where our posts live
  }),
  /*
    NOTE: Right now the schema for our post frontmatter is a bit wonky. As much as I'd like to have 100% control over post frontmatter, doing so would require effort I'm unwilling to expend at the moment, so here's how it's gonna be.

    The important top-level frontmatter will be maintained, but everything else will be read from "dg-note-properties" which is our raw obsidian note properties pass on as is, no processing by the digitalgarden plugin.

    Though I'd prefer if properties under "dg-note-properties", and in fact, we can do this by setting `dg-pass-frontmatter` to true, however, doing so risks collisions with plugin computer frontmatter properties. Moreover, in the case of a collision the plugin's computed properties would win, which kinda defeats the point

    For now, we'll keep things like this until the astro rewrite is done and perhaps for some time beyond that, until I decide to move away from the digitalgarden plugin entirely.

    For now though, regarding property access, we can always use zod's transform method to make it more "ergonomic"
  */
  // TODO: Update the note properties in the vault to align with this schema before this is merged into main
  // TODO: Mirror the local note renames in the vault (see TODO.md) — filenames must not contain "?" or "#":
  // Astro's content layer addresses files as file:// URLs, so those characters truncate the path and the
  // note is silently dropped from the collection. Punctuation belongs in the "title" property instead.
  schema: () =>
    z
      .object({
        "dg-publish": z.boolean(), // Most important
        tags: z.array(z.string()), // Solely for checking for "gardenEntry" to determine the home/index page
        "dg-path": z.string(), // The path to our post, auto-generated by the digitalgarden plugin per our plugin settings and path rewrite rules. We do not manually set this
        permalink: z.string(), // The actual URL for a post
        "dg-permalink": z.string(), // Setting this is what allows us full control over the URLs for our posts. Otherwise, the digitalgarden plugin will auto gen the "permalink" property from the "dg-path" property. This property exists solely as a means for user override. The actual URL is set using the "permalink" prop. Must always be manually set to enforce that we determine the URLs, not the plugin.
        "dg-hide": z.boolean().optional(),
        "dg-note-properties": z.object({
          title: z.string(),
          description: z.string(),
          tags: z.array(z.string()),
          published: z.string(),
          last_updated: z.string(),
        }),
      })
      .transform(({ "dg-note-properties": rawNoteProps, ...pluginProps }) => ({
        rawNoteProps,
        pluginProps,
      })),
});

export const collections = {
  posts,
};
